services:
  web:
    build: .
    image: eduarpj/asistente-auditoria:latest
    container_name: asistente-auditoria
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
